#############################################################################
# Makefile for building: PwhManagementProject
# Generated by qmake (3.1) (Qt 5.9.0)
# Project:  PwhManagementProject.pro
# Template: app
# Command: D:/qt-build/qt/bin/qmake.exe -o Makefile PwhManagementProject.pro -spec win32-g++ CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

first: debug
install: debug-install
uninstall: debug-uninstall
QMAKE         = D:/qt-build/qt/bin/qmake.exe
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = cp -f
INSTALL_PROGRAM = cp -f
INSTALL_DIR   = cp -f -R
QINSTALL_FILE = D:/qt-build/qt/bin/qmake.exe -install qinstall file
QINSTALL_PROGRAM = D:/qt-build/qt/bin/qmake.exe -install qinstall program
DEL_FILE      = rm -f
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		debug \
		release


debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: PwhManagementProject.pro D:/qt-build/qt/mkspecs/win32-g++/qmake.conf D:/qt-build/qt/mkspecs/features/spec_pre.prf \
		D:/qt-build/qt/mkspecs/qdevice.pri \
		D:/qt-build/qt/mkspecs/features/device_config.prf \
		D:/qt-build/qt/mkspecs/common/g++-base.conf \
		D:/qt-build/qt/mkspecs/common/windows-gles.conf \
		D:/qt-build/qt/mkspecs/common/sanitize.conf \
		D:/qt-build/qt/mkspecs/common/gcc-base.conf \
		D:/qt-build/qt/mkspecs/qconfig.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_av.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_av_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_avwidgets.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_avwidgets_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_axbase.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_axbase_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_axcontainer.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_axcontainer_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_axserver.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_axserver_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_bluetooth.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_bluetooth_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_charts.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_charts_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_concurrent.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_contacts.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_contacts_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_core.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_core_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_dbus.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_docgallery.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_docgallery_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_gamepad.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_gamepad_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_gui.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_gui_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_network.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_network_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_nfc.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_nfc_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_opengl.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_organizer.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_organizer_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_printsupport.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_publishsubscribe.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_publishsubscribe_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_purchasing.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_purchasing_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_qml.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_qml_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_qmltest.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_quick.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_quick_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_remoteobjects.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_repparser.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_repparser_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_scxml.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_scxml_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_serialbus.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_serialbus_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_serialport.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_serialport_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_serviceframework.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_serviceframework_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_sql.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_sql_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_svg.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_svg_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_testlib.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_versit.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_versit_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_versitorganizer.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_versitorganizer_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_websockets.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_websockets_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_widgets.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_xml.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_xml_private.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		D:/qt-build/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		D:/qt-build/qt/mkspecs/features/qt_functions.prf \
		D:/qt-build/qt/mkspecs/features/qt_config.prf \
		D:/qt-build/qt/mkspecs/win32-g++/qmake.conf \
		D:/qt-build/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		D:/qt-build/qt/mkspecs/features/exclusive_builds.prf \
		D:/qt-build/qt/mkspecs/features/toolchain.prf \
		D:/qt-build/qt/mkspecs/features/default_pre.prf \
		D:/qt-build/qt/mkspecs/features/win32/default_pre.prf \
		D:/qt-build/qt/mkspecs/features/resolve_config.prf \
		D:/qt-build/qt/mkspecs/features/exclusive_builds_post.prf \
		D:/qt-build/qt/mkspecs/features/default_post.prf \
		D:/qt-build/qt/mkspecs/features/qml_debug.prf \
		D:/qt-build/qt/mkspecs/features/precompile_header.prf \
		D:/qt-build/qt/mkspecs/features/warn_on.prf \
		D:/qt-build/qt/mkspecs/features/qt.prf \
		D:/qt-build/qt/mkspecs/features/resources.prf \
		D:/qt-build/qt/mkspecs/features/moc.prf \
		D:/qt-build/qt/mkspecs/features/win32/opengl.prf \
		D:/qt-build/qt/mkspecs/features/uic.prf \
		D:/qt-build/qt/mkspecs/features/av.prf \
		D:/qt-build/qt/mkspecs/features/avwidgets.prf \
		D:/qt-build/qt/mkspecs/features/qmake_use.prf \
		D:/qt-build/qt/mkspecs/features/file_copies.prf \
		D:/qt-build/qt/mkspecs/features/win32/windows.prf \
		D:/qt-build/qt/mkspecs/features/testcase_targets.prf \
		D:/qt-build/qt/mkspecs/features/exceptions.prf \
		D:/qt-build/qt/mkspecs/features/yacc.prf \
		D:/qt-build/qt/mkspecs/features/lex.prf \
		PwhManagementProject.pro \
		D:/qt-build/qt/lib/qtmaind.prl \
		D:/qt-build/qt/lib/Qt5OpenGL.prl \
		D:/qt-build/qt/lib/Qt5Widgets.prl \
		D:/qt-build/qt/lib/Qt5Gui.prl \
		D:/qt-build/qt/lib/Qt5Core.prl
	$(QMAKE) -o Makefile PwhManagementProject.pro -spec win32-g++ CONFIG+=qml_debug
D:/qt-build/qt/mkspecs/features/spec_pre.prf:
D:/qt-build/qt/mkspecs/qdevice.pri:
D:/qt-build/qt/mkspecs/features/device_config.prf:
D:/qt-build/qt/mkspecs/common/g++-base.conf:
D:/qt-build/qt/mkspecs/common/windows-gles.conf:
D:/qt-build/qt/mkspecs/common/sanitize.conf:
D:/qt-build/qt/mkspecs/common/gcc-base.conf:
D:/qt-build/qt/mkspecs/qconfig.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_av.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_av_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_avwidgets.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_avwidgets_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_axbase.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_axbase_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_axcontainer.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_axcontainer_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_axserver.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_axserver_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_bluetooth.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_bluetooth_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_bootstrap_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_charts.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_charts_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_concurrent.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_contacts.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_contacts_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_core.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_core_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_dbus.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_dbus_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_docgallery.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_docgallery_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_fb_support_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_gamepad.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_gamepad_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_gui.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_gui_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_network.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_network_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_nfc.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_nfc_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_opengl.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_opengl_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_openglextensions.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_openglextensions_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_organizer.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_organizer_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_printsupport.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_publishsubscribe.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_publishsubscribe_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_purchasing.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_purchasing_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_qml.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_qml_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_qmldebug_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_qmltest.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_quick.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_quick_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_remoteobjects.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_remoteobjects_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_repparser.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_repparser_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_scxml.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_scxml_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_serialbus.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_serialbus_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_serialport.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_serialport_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_serviceframework.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_serviceframework_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_sql.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_sql_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_svg.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_svg_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_testlib.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_testlib_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_theme_support_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_versit.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_versit_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_versitorganizer.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_versitorganizer_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_websockets.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_websockets_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_widgets.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_widgets_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_xml.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_xml_private.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_xmlpatterns.pri:
D:/qt-build/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
D:/qt-build/qt/mkspecs/features/qt_functions.prf:
D:/qt-build/qt/mkspecs/features/qt_config.prf:
D:/qt-build/qt/mkspecs/win32-g++/qmake.conf:
D:/qt-build/qt/mkspecs/features/spec_post.prf:
.qmake.stash:
D:/qt-build/qt/mkspecs/features/exclusive_builds.prf:
D:/qt-build/qt/mkspecs/features/toolchain.prf:
D:/qt-build/qt/mkspecs/features/default_pre.prf:
D:/qt-build/qt/mkspecs/features/win32/default_pre.prf:
D:/qt-build/qt/mkspecs/features/resolve_config.prf:
D:/qt-build/qt/mkspecs/features/exclusive_builds_post.prf:
D:/qt-build/qt/mkspecs/features/default_post.prf:
D:/qt-build/qt/mkspecs/features/qml_debug.prf:
D:/qt-build/qt/mkspecs/features/precompile_header.prf:
D:/qt-build/qt/mkspecs/features/warn_on.prf:
D:/qt-build/qt/mkspecs/features/qt.prf:
D:/qt-build/qt/mkspecs/features/resources.prf:
D:/qt-build/qt/mkspecs/features/moc.prf:
D:/qt-build/qt/mkspecs/features/win32/opengl.prf:
D:/qt-build/qt/mkspecs/features/uic.prf:
D:/qt-build/qt/mkspecs/features/av.prf:
D:/qt-build/qt/mkspecs/features/avwidgets.prf:
D:/qt-build/qt/mkspecs/features/qmake_use.prf:
D:/qt-build/qt/mkspecs/features/file_copies.prf:
D:/qt-build/qt/mkspecs/features/win32/windows.prf:
D:/qt-build/qt/mkspecs/features/testcase_targets.prf:
D:/qt-build/qt/mkspecs/features/exceptions.prf:
D:/qt-build/qt/mkspecs/features/yacc.prf:
D:/qt-build/qt/mkspecs/features/lex.prf:
PwhManagementProject.pro:
D:/qt-build/qt/lib/qtmaind.prl:
D:/qt-build/qt/lib/Qt5OpenGL.prl:
D:/qt-build/qt/lib/Qt5Widgets.prl:
D:/qt-build/qt/lib/Qt5Gui.prl:
D:/qt-build/qt/lib/Qt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile PwhManagementProject.pro -spec win32-g++ CONFIG+=qml_debug

qmake_all: FORCE

make_first: debug-make_first release-make_first  FORCE
all: debug-all release-all  FORCE
clean: debug-clean release-clean  FORCE
distclean: debug-distclean release-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash

debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables

check: first

benchmark: first
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
